In [1]:
import numpy as np

# Step 1: Set up student credentials
STUDENT_NAME = "Calvin" 
STUDENT_ID = 250698

print(f"--- {STUDENT_NAME}'s Final Array Analysis ---\n")

# Step 2: Set the random seed using the Student ID
np.random.seed(STUDENT_ID)

# Step 3: Generate the random data
# The upper limit uses the last two digits of your ID (98) plus 50
max_value = (STUDENT_ID % 100) + 50
data = np.random.randint(1, max_value, size=10)

print(f"Generated Array: {data}\n")

# Step 4: Calculate statistics
mean_val = np.mean(data)
std_val = np.std(data)

# Step 5: Print results (rounded to 2 decimal places for neatness)
print(f"Mean (Average):     {mean_val:.2f}")
print(f"Standard Deviation: {std_val:.2f}")

--- Calvin's Final Array Analysis ---

Generated Array: [ 74  34 141 120  74  14  67   7  13  19]

Mean (Average):     56.30
Standard Deviation: 44.67


In [2]:
import numpy as np

# Step 1: Set up student credentials
STUDENT_NAME = "Calvin"
STUDENT_ID = 250698

print(f"--- {STUDENT_NAME}'s Matrix Analysis ---\n")

# Step 2: Set the random seed using the Student ID
np.random.seed(STUDENT_ID)

# Step 3: Generate a 3x4 matrix
# The upper limit uses (250698 % 50) + 20 = 48 + 20 = 68
max_value = (STUDENT_ID % 50) + 20
matrix = np.random.randint(1, max_value, size=(3, 4))

print(f"Generated Matrix:\n{matrix}\n")

# Step 4: Calculate row and column sums
row_sums = np.sum(matrix, axis=1) 
col_sums = np.sum(matrix, axis=0) 

# Step 5: Print results
print("Row sums:", row_sums)
print("Column sums:", col_sums)

--- Calvin's Matrix Analysis ---

Generated Matrix:
[[34 13 14 67]
 [62 21  7 13]
 [19  9 60 33]]

Row sums: [128 103 121]
Column sums: [115  43  81 113]


In [3]:
import numpy as np

# Step 1: Set up student credentials
STUDENT_NAME = "Calvin"
STUDENT_ID = 250698

print(f"--- {STUDENT_NAME}'s 3D Array Analysis ---\n")

# Step 2: Set the random seed
np.random.seed(STUDENT_ID)

# Step 3: Generate a 3x3x3 array
# The upper limit uses (250698 % 20) + 10 = 18 + 10 = 28
max_value = (STUDENT_ID % 20) + 10
arr3d = np.random.randint(0, max_value, size=(3, 3, 3))

print(f"Generated 3D Array:\n{arr3d}\n")

# Step 4: Extract a 2D slice 
slice_mid = arr3d[:, 1, :]
print("Middle Slice [:, 1, :]:\n", slice_mid)

--- Calvin's 3D Array Analysis ---

Generated 3D Array:
[[[ 9  1 25]
  [15 11 12]
  [23  9 13]]

 [[ 2 20 20]
  [ 6  6 12]
  [18  8 27]]

 [[ 0  4 12]
  [22 16  3]
  [ 1 24 16]]]

Middle Slice [:, 1, :]:
 [[15 11 12]
 [ 6  6 12]
 [22 16  3]]


In [4]:
import numpy as np

# Step 1: Set up student credentials
STUDENT_NAME = "Calvin"
STUDENT_ID = 250698

print(f"--- {STUDENT_NAME}'s Array Filtering Analysis ---\n")

# Step 2: Set the random seed
np.random.seed(STUDENT_ID)

# Step 3: Generate the array
# The upper limit uses (250698 % 100) + 50 = 98 + 50 = 148
max_value = (STUDENT_ID % 100) + 50
x = np.random.randint(1, max_value, size=10)

# Step 4: Filter the array
# Lower bound: 250698 % 50 = 48
# Upper bound: 250698 % 100 = 98
# Filter condition: Keep numbers strictly greater than 48 AND strictly less than 98
lower_bound = STUDENT_ID % 50
upper_bound = STUDENT_ID % 100
filtered = x[(x > lower_bound) & (x < upper_bound)]

# Step 5: Print results
print(f"Original Array: {x}")
print(f"Filtered subset (>{lower_bound} and <{upper_bound}): {filtered}")

--- Calvin's Array Filtering Analysis ---

Original Array: [ 74  34 141 120  74  14  67   7  13  19]
Filtered subset (>48 and <98): [74 74 67]


In [5]:
import numpy as np

# Step 1: Set up student credentials
STUDENT_NAME = "Calvin"
STUDENT_ID = 250698

print(f"--- {STUDENT_NAME}'s Linear Algebra Analysis ---\n")

# Step 2: Set the random seed
np.random.seed(STUDENT_ID)

# Step 3: Generate two 2x2 matrices
# The upper limit uses (250698 % 50) + 20 = 48 + 20 = 68
max_value = (STUDENT_ID % 50) + 20
A = np.random.randint(1, max_value, size=(2, 2))
B = np.random.randint(1, max_value, size=(2, 2)) 

print("Matrix A:\n", A, "\n")
print("Matrix B:\n", B, "\n")

# Step 4: Perform matrix operations
product = A @ B  # Matrix multiplication (dot product)
det_A = np.linalg.det(A) # Determinant of Matrix A

# Step 5: Print results
print("A @ B (Matrix Multiplication):\n", product, "\n")
# Rounded to 2 decimal places because determinants often become floats
print(f"Determinant of A: {det_A:.2f}")

--- Calvin's Linear Algebra Analysis ---

Matrix A:
 [[34 13]
 [14 67]] 

Matrix B:
 [[62 21]
 [ 7 13]] 

A @ B (Matrix Multiplication):
 [[2199  883]
 [1337 1165]] 

Determinant of A: 2096.00


In [6]:
import numpy as np

# Step 1: Set up student credentials
STUDENT_NAME = "Calvin"
STUDENT_ID = 250698

print(f"--- {STUDENT_NAME}'s Trigonometry Analysis ---\n")

# Step 2: Generate 8 evenly spaced angles from 0 to 2*pi (a full circle)
angles = np.linspace(0, 2 * np.pi, 8) 

# Step 3: Calculate the sine and cosine for each angle
sine_vals = np.sin(angles) 
cos_vals = np.cos(angles)

# Step 4: Print results
print("Angles (in radians):\n", angles, "\n")
print("Sine values:\n", sine_vals, "\n")
print("Cosine values:\n", cos_vals)

--- Calvin's Trigonometry Analysis ---

Angles (in radians):
 [0.         0.8975979  1.7951958  2.6927937  3.5903916  4.48798951
 5.38558741 6.28318531] 

Sine values:
 [ 0.00000000e+00  7.81831482e-01  9.74927912e-01  4.33883739e-01
 -4.33883739e-01 -9.74927912e-01 -7.81831482e-01 -2.44929360e-16] 

Cosine values:
 [ 1.          0.6234898  -0.22252093 -0.90096887 -0.90096887 -0.22252093
  0.6234898   1.        ]


In [7]:
import numpy as np

# Step 1: Set up student credentials
STUDENT_NAME = "Calvin"
STUDENT_ID = 250698

print(f"--- {STUDENT_NAME}'s Array Slicing Analysis ---\n")

# Step 2: Set the random seed
np.random.seed(STUDENT_ID)

# Step 3: Generate a 4x4 matrix
# The upper limit uses (250698 % 50) + 20 = 48 + 20 = 68
max_value = (STUDENT_ID % 50) + 20
arr = np.random.randint(1, max_value, size=(4, 4))

print("Original Generated Array:")
print(arr, "\n")

# Step 4: Modify the array using step slicing
# This targets every 2nd row and every 2nd column, starting from index 0
arr[::2, ::2] = 0

# Step 5: Print the final modified array
print(f"{STUDENT_NAME}'s Modified 4x4 Array:\n{arr}")

--- Calvin's Array Slicing Analysis ---

Original Generated Array:
[[34 13 14 67]
 [62 21  7 13]
 [19  9 60 33]
 [37 66 17 46]] 

Calvin's Modified 4x4 Array:
[[ 0 13  0 67]
 [62 21  7 13]
 [ 0  9  0 33]
 [37 66 17 46]]


In [8]:
import numpy as np

# Step 1: Set up student credentials
STUDENT_NAME = "Calvin"
STUDENT_ID = 250698

print(f"--- {STUDENT_NAME}'s Grading Analysis ---\n")

# Step 2: Set the random seed
np.random.seed(STUDENT_ID)

# Step 3: Generate the scores
# The upper limit uses (250698 % 100) + 50 = 98 + 50 = 148
max_value = (STUDENT_ID % 100) + 50
scores = np.random.randint(0, max_value, 10)

# Step 4: Calculate Pass/Fail grades
# The passing threshold uses 250698 % 70 = 28
pass_threshold = STUDENT_ID % 70
grades = np.where(scores >= pass_threshold, 'Pass', 'Fail')

# Step 5: Print results
print(f"Passing Threshold: {pass_threshold}\n")
print("Scores:", scores)
print("Grades:", grades)

--- Calvin's Grading Analysis ---

Passing Threshold: 28

Scores: [ 73  33 140 119  73  13  66   6  12  18]
Grades: ['Pass' 'Pass' 'Pass' 'Pass' 'Pass' 'Fail' 'Pass' 'Fail' 'Fail' 'Fail']


In [9]:
import numpy as np

STUDENT_NAME = "Calvin"
STUDENT_ID = 250698

np.random.seed(STUDENT_ID)

# Generate a 3x4 matrix
# Max value: (250698 % 50) + 20 = 68
arr = np.random.randint(1, (STUDENT_ID % 50) + 20, size=(3, 4))

# Reshaping operations
flat_arr = arr.flatten()
transposed_arr = arr.T

print("Original array:\n", arr)
print("\nFlattened:", flat_arr)
print("\nTransposed:\n", transposed_arr)


Original array:
 [[34 13 14 67]
 [62 21  7 13]
 [19  9 60 33]]

Flattened: [34 13 14 67 62 21  7 13 19  9 60 33]

Transposed:
 [[34 62 19]
 [13 21  9]
 [14  7 60]
 [67 13 33]]


In [10]:
import numpy as np

STUDENT_NAME = "Calvin"
STUDENT_ID = 250698

np.random.seed(STUDENT_ID)
arr = np.random.randint(1, STUDENT_ID % 50 + 20, (3,3))
mask = arr % 2 == 0
arr[mask] = -1

print("Array with conditional replacements:\n", arr)

Array with conditional replacements:
 [[-1 13 -1]
 [67 -1 21]
 [ 7 13 19]]


In [11]:
import numpy as np
import pandas as pd

STUDENT_NAME = "Calvin"
STUDENT_ID = 250698

np.random.seed(STUDENT_ID)

# Create the DataFrame with personalized values
df = pd.DataFrame({
    'Name': [STUDENT_NAME] * 5,
    'Score': np.random.randint(STUDENT_ID % 50, (STUDENT_ID % 100) + 50, 5),
    'YearsCodePro': np.random.randint(0, (STUDENT_ID % 20) + 10, 5)
})

print(df)

     Name  Score  YearsCodePro
0  Calvin    121            13
1  Calvin     81             2
2  Calvin    127            20
3  Calvin     60            20
4  Calvin    121             6


In [12]:
import numpy as np
import pandas as pd

STUDENT_NAME = "Calvin"
STUDENT_ID = 250698

np.random.seed(STUDENT_ID)

df = pd.DataFrame({
    'EdLevel': ['Bachelor', 'Master', 'PhD', 'Bachelor', 'Master'],
    'ConvertedComp': np.random.randint(40000, 150000, 5)
})

avg_salary = df.groupby('EdLevel')['ConvertedComp'].mean()

print(avg_salary)

EdLevel
Bachelor    107852.0
Master      104134.0
PhD         121657.0
Name: ConvertedComp, dtype: float64


In [13]:
import numpy as np
import pandas as pd

STUDENT_NAME = "Calvin"
STUDENT_ID = 250698

np.random.seed(STUDENT_ID)

df = pd.DataFrame({
    'Country': ['Philippines', 'USA', 'UK', 'Canada', 'Germany'],
    'ConvertedComp': np.random.randint(40000, 150000, 5)
})

top5 = df.sort_values(by='ConvertedComp', ascending=False)

print(top5)

       Country  ConvertedComp
4      Germany         134187
2           UK         121657
3       Canada         118543
0  Philippines          97161
1          USA          74081


In [14]:
import numpy as np
import pandas as pd

STUDENT_NAME = "Calvin"
STUDENT_ID = 250698

np.random.seed(STUDENT_ID)

# Create DataFrame
# YearsCodePro range: 0 to (18 + 10) = 28
df = pd.DataFrame({
    'Name': [STUDENT_NAME] * 5,
    'YearsCodePro': np.random.randint(0, (STUDENT_ID % 20) + 10, 5)
})

# Filter: YearsCodePro > (250698 % 10) = 8
high_exp = df[df['YearsCodePro'] > (STUDENT_ID % 10)]

print(high_exp)

     Name  YearsCodePro
0  Calvin             9
2  Calvin            25
3  Calvin            15
4  Calvin            11


In [15]:
import numpy as np
import pandas as pd

STUDENT_NAME = "Calvin"
STUDENT_ID = 250698

np.random.seed(STUDENT_ID)

# Create DataFrame with random salaries
df = pd.DataFrame({'ConvertedComp': np.random.randint(40000, 150000, 5)})

# Define bin ranges and labels
bins = [0, 50000, 100000, 150000, 200000]
labels = ['0-50k', '50-100k', '100-150k', '>150k']

# Segment the salaries into brackets
df['Bracket'] = pd.cut(df['ConvertedComp'], bins=bins, labels=labels)

print(df)

   ConvertedComp   Bracket
0          97161   50-100k
1          74081   50-100k
2         121657  100-150k
3         118543  100-150k
4         134187  100-150k


In [16]:
import numpy as np
import pandas as pd

STUDENT_NAME = "Calvin"
STUDENT_ID = 250698

np.random.seed(STUDENT_ID)

# Create DataFrame with random salaries
df = pd.DataFrame({'ConvertedComp': np.random.randint(40000, 150000, 5)})

# Apply natural log transformation to the compensation data
df['LogComp'] = np.log(df['ConvertedComp'])

print(df)

   ConvertedComp    LogComp
0          97161  11.484125
1          74081  11.212914
2         121657  11.708961
3         118543  11.683031
4         134187  11.806990


In [17]:
import numpy as np
import pandas as pd

STUDENT_NAME = "Calvin"
STUDENT_ID = 250698

np.random.seed(STUDENT_ID)

# Create DataFrame with personalized random data
df = pd.DataFrame({
    'YearsCodePro': np.random.randint(0, (STUDENT_ID % 20) + 10, 5),
    'ConvertedComp': np.random.randint(40000, 150000, 5)
})

# Calculate the correlation matrix
corr_matrix = df.corr()

print("Correlation Matrix:\n", corr_matrix)

Correlation Matrix:
                YearsCodePro  ConvertedComp
YearsCodePro       1.000000      -0.461312
ConvertedComp     -0.461312       1.000000


In [18]:
import numpy as np
import pandas as pd

STUDENT_NAME = "Calvin"
STUDENT_ID = 250698

np.random.seed(STUDENT_ID)

df = pd.DataFrame({
    'EdLevel': ['Bachelor', 'Master', 'PhD', 'Bachelor', 'Master'],
    'ConvertedComp': np.random.randint(40000, 150000, 5)
})

# Calculate mean, median, and standard deviation for each 'EdLevel'
summary = df.groupby('EdLevel')['ConvertedComp'].agg(['mean', 'median', 'std']).reset_index()

print(summary)

    EdLevel      mean    median           std
0  Bachelor  107852.0  107852.0  15119.357195
1    Master  104134.0  104134.0  42501.360190
2       PhD  121657.0  121657.0           NaN


In [19]:
import numpy as np
import pandas as pd

STUDENT_NAME = "Calvin"
STUDENT_ID = 250698

np.random.seed(STUDENT_ID)

# Generate random salaries
df = pd.DataFrame({
    'ConvertedComp': np.random.randint(40000, 150000, 5)
})

# Define the pay threshold
threshold = 110000

# Create the 'HighPay' column using np.where()
df['HighPay'] = np.where(df['ConvertedComp'] > threshold, 'Yes', 'No')

print(df)

   ConvertedComp HighPay
0          97161      No
1          74081      No
2         121657     Yes
3         118543     Yes
4         134187     Yes


In [20]:
import numpy as np
import pandas as pd

STUDENT_NAME = "Calvin"
STUDENT_ID = 250698

np.random.seed(STUDENT_ID)

# Create DataFrame with countries and random salaries
df = pd.DataFrame({
    'Country': ['Philippines', 'USA', 'UK', 'Canada', 'Germany'],
    'ConvertedComp': np.random.randint(40000, 150000, 5)
})

# Group by 'Country' and calculate the mean and max 'ConvertedComp'
top_countries = df.groupby('Country')['ConvertedComp'].agg(['mean', 'max'])

print(top_countries)

                 mean     max
Country                      
Canada       118543.0  118543
Germany      134187.0  134187
Philippines   97161.0   97161
UK           121657.0  121657
USA           74081.0   74081
