In [1]:
# Step 1: Import NumPy
import numpy as np

# Step 2: Create a 1D array representing years of experience
years_exp = np.array([1, 3, 5, 7, 10])
print("--- Years of Experience ---")
print(years_exp, "\n")

# Step 3: Create a 2D array representing sample salaries (in thousands)
salaries = np.array([[50, 60, 70], 
                     [80, 90, 100]])
print("--- Salary Matrix ---")
print(salaries, "\n")

# Step 4: Create an array of zeros and ones for placeholder analysis
zeros_array = np.zeros((2, 2)) # 2x2 zeros
ones_array = np.ones((2, 3))   # 2x3 ones
print("--- Zeros Array ---")
print(zeros_array, "\n")
print("--- Ones Array ---")
print(ones_array, "\n")

--- Years of Experience ---
[ 1  3  5  7 10] 

--- Salary Matrix ---
[[ 50  60  70]
 [ 80  90 100]] 

--- Zeros Array ---
[[0. 0.]
 [0. 0.]] 

--- Ones Array ---
[[1. 1. 1.]
 [1. 1. 1.]] 



In [2]:
import numpy as np
years_exp = np.array([1, 3, 5, 7, 10])

# Step 1: Element-wise addition
exp_plus_5 = years_exp + 5 # Add 5 years to all experience values
print("Years + 5:", exp_plus_5)

# Step 2: Element-wise multiplication
exp_times_2 = years_exp * 2 # Multiply all values by 2
print("Years * 2:", exp_times_2)

# Step 3: Dot product (simulate salary projections)
sample1 = np.array([1, 2, 3])
sample2 = np.array([4, 5, 6])
dot_result = np.dot(sample1, sample2)
print("Dot Product:", dot_result)

Years + 5: [ 6  8 10 12 15]
Years * 2: [ 2  6 10 14 20]
Dot Product: 32


In [3]:
import numpy as np
years_exp = np.array([1, 3, 5, 7, 10])
salaries = np.array([[50, 60, 70], 
                     [80, 90, 100]])

print("--- Array Indexing & Slicing ---\n")

# Step 1: Access an individual element (Python is 0-indexed)
print("First year of experience:", years_exp[0])

# Step 2: Slice arrays (First two elements of the first row)
print("First two salaries:", salaries[0, :2]) 

# Step 3: Access all rows for a specific column (The ':' means 'all rows')
print("Second column salaries:", salaries[:, 1])

# Step 4: Negative indexing (-1 always grabs the very last element)
print("Last year of experience:", years_exp[-1])

--- Array Indexing & Slicing ---

First year of experience: 1
First two salaries: [50 60]
Second column salaries: [60 90]
Last year of experience: 10


In [4]:
import numpy as np

print("--- Array Reshaping & Manipulation ---\n")

# Step 1: Reshape 1D array into 2x3 matrix for batch analysis
reshaped_exp = np.reshape(np.arange(1, 7), (2, 3))
print("Reshaped Experience Array:\n", reshaped_exp, "\n")

# Step 2: Flatten 2D arrays back into 1D
flattened_exp = reshaped_exp.flatten()
print("Flattened Array:", flattened_exp, "\n")

# Step 3: Transpose example (swaps rows and columns)
print("Transposed Array:\n", reshaped_exp.T)

--- Array Reshaping & Manipulation ---

Reshaped Experience Array:
 [[1 2 3]
 [4 5 6]] 

Flattened Array: [1 2 3 4 5 6] 

Transposed Array:
 [[1 4]
 [2 5]
 [3 6]]


In [5]:
import numpy as np

salaries = np.array([[50, 60, 70], 
                     [80, 90, 100]])

print("--- Broadcasting Example ---\n")

# Step 1: Add a bonus array to salaries using broadcasting
bonus = np.array([5, 10, 15])

salaries_with_bonus = salaries + bonus 

print("Original Salaries:\n", salaries, "\n")
print("Bonus Array:", bonus, "\n")
print("Salaries after bonus:\n", salaries_with_bonus)

--- Broadcasting Example ---

Original Salaries:
 [[ 50  60  70]
 [ 80  90 100]] 

Bonus Array: [ 5 10 15] 

Salaries after bonus:
 [[ 55  70  85]
 [ 85 100 115]]


In [6]:
import numpy as np

years_exp = np.array([1, 3, 5, 7, 10])
salaries = np.array([[50, 60, 70], 
                     [80, 90, 100]])

print("--- Statistical Analysis ---\n")

# Step 1: Mean (average) of years of experience
print("Mean experience:", np.mean(years_exp))

# Step 2: Standard deviation of experience (how spread out the numbers are)
print("Std deviation of experience:", np.std(years_exp))

# Step 3: Max and Min salaries
print("Max salary:", np.max(salaries))
print("Min salary:", np.min(salaries))

# Step 4: Sum of salaries
print("Sum of all salaries:", np.sum(salaries))

--- Statistical Analysis ---

Mean experience: 5.2
Std deviation of experience: 3.1240998703626617
Max salary: 100
Min salary: 50
Sum of all salaries: 450


In [7]:
# Step 1: Apply trigonometric functions
angles = np.array([0, np.pi/4, np.pi/2])
print("Sine of angles:", np.sin(angles))
print("Cosine of angles:", np.cos(angles))
# Step 2: Apply function along rows (sum salaries per person)
salary_sums = np.apply_along_axis(np.sum, 1, salaries)
print("Sum of Salaries per person:", salary_sums)


Sine of angles: [0.         0.70710678 1.        ]
Cosine of angles: [1.00000000e+00 7.07106781e-01 6.12323400e-17]
Sum of Salaries per person: [180 270]


In [8]:
import numpy as np
import pandas as pd  # <-- This is the missing line!

# Step 1: Create a NumPy array of random data
data = np.random.randint(1, 50, size=(5, 3))

# Step 2: Convert the array into a DataFrame
df_data = pd.DataFrame(data, columns=['X', 'Y', 'Z'])
print("Generated Data:\n", df_data, "\n")

# Step 3: Apply NumPy functions to DataFrame columns
df_data['Log_X'] = np.log(df_data['X'])
df_data['Sqrt_Y'] = np.sqrt(df_data['Y'])
print("DataFrame with NumPy Transformations:\n", df_data, "\n")

# Step 4: Analyze data using Pandas correlation
print("Correlation Matrix:\n", df_data.corr())

Generated Data:
     X   Y   Z
0  21  40  34
1  39  34  21
2  20  11  22
3  30   7  22
4  16  23  41 

DataFrame with NumPy Transformations:
     X   Y   Z     Log_X    Sqrt_Y
0  21  40  34  3.044522  6.324555
1  39  34  21  3.663562  5.830952
2  20  11  22  2.995732  3.316625
3  30   7  22  3.401197  2.645751
4  16  23  41  2.772589  4.795832 

Correlation Matrix:
                X         Y         Z     Log_X    Sqrt_Y
X       1.000000  0.125251 -0.714939  0.992814  0.089455
Y       0.125251  1.000000  0.375583  0.083803  0.995119
Z      -0.714939  0.375583  1.000000 -0.760270  0.415286
Log_X   0.992814  0.083803 -0.760270  1.000000  0.038279
Sqrt_Y  0.089455  0.995119  0.415286  0.038279  1.000000


In [9]:
import numpy as np
import pandas as pd

# Re-creating the DataFrame from the previous step so the code runs
data = np.random.randint(1, 50, size=(5, 3))
df_data = pd.DataFrame(data, columns=['X', 'Y', 'Z'])

# Step 1: Save the DataFrame to a CSV file
df_data.to_csv('sample_data.csv', index=False)
print("Data saved to 'sample_data.csv'.\n")

# Step 2: Load the CSV file back into a new DataFrame
df_imported = pd.read_csv('sample_data.csv')
print("Imported DataFrame:\n", df_imported, "\n")

# Step 3: Generate summary statistics
summary_stats = df_imported.describe()
print("Summary Statistics:\n", summary_stats, "\n")

# Step 4: Display column means and standard deviations
print("Column Means:\n", df_imported.mean(), "\n")
print("Column Standard Deviations:\n", df_imported.std())

Data saved to 'sample_data.csv'.

Imported DataFrame:
     X   Y   Z
0  49   1  13
1  45  35  19
2   6  16  12
3  34   3   1
4  20  15  42 

Summary Statistics:
                X         Y         Z
count   5.000000   5.00000   5.00000
mean   30.800000  14.00000  17.40000
std    17.852171  13.56466  15.20855
min     6.000000   1.00000   1.00000
25%    20.000000   3.00000  12.00000
50%    34.000000  15.00000  13.00000
75%    45.000000  16.00000  19.00000
max    49.000000  35.00000  42.00000 

Column Means:
 X    30.8
Y    14.0
Z    17.4
dtype: float64 

Column Standard Deviations:
 X    17.852171
Y    13.564660
Z    15.208550
dtype: float64


In [10]:
import pandas as pd
import numpy as np

print("--- Testing Groupby Logic on Dummy Data ---\n")

# Step 1: Load the dummy data you already have
df_data = pd.read_csv('modified_data.csv')
print("Loaded Dataset:\n", df_data.head(), "\n")

# Step 2: Select relevant columns (the ones that actually exist!)
df_subset = df_data[['X', 'Y', 'Sum_XY']]
print("Subset of Data:\n", df_subset.head(), "\n")

# Step 3: Clean the data
df_clean = df_subset.dropna().copy()

# Step 4: Categorize X into groups 
# (Assigns 'High' if X is 30 or greater, otherwise 'Low')
df_clean['X_Category'] = np.where(df_clean['X'] >= 30, 'High', 'Low')

# Step 5: Group data by the new category, compute average of Y
grouped_data = df_clean.groupby(['X_Category'])['Y'].mean()
print("Grouped Average of Y:\n", grouped_data.head(), "\n")

# Step 6: Reset index for readability
grouped_data = grouped_data.reset_index()
print("Formatted Grouped Data:\n", grouped_data.head())

--- Testing Groupby Logic on Dummy Data ---

Loaded Dataset:
     X   Y   Z  Sum_XY
0  39  29  15      68
1  43   8  21      51
2  39  19  23      58
3  11  11  24      22
4  36  40  24      76 

Subset of Data:
     X   Y  Sum_XY
0  39  29      68
1  43   8      51
2  39  19      58
3  11  11      22
4  36  40      76 

Grouped Average of Y:
 X_Category
High    24.0
Low     11.0
Name: Y, dtype: float64 

Formatted Grouped Data:
   X_Category     Y
0       High  24.0
1        Low  11.0
