In [1]:
# Step 1: Import NumPy
import numpy as np

# Step 2: Create a 1D array representing years of experience
years_exp = np.array([1, 3, 5, 7, 10, 12, 15])
print("--- Years of Experience ---")
print(years_exp, "\n")

# Step 3: Create a 2D array representing sample salaries (in thousands)
salaries = np.array([[50, 60, 70, 75, 80], 
                     [80, 90, 100, 110, 120]])
print("--- Salary Matrix ---")
print(salaries, "\n")

# Step 4: Create an array of zeros and ones for placeholder analysis
zeros_array = np.zeros((2, 2)) # 2x2 zeros
ones_array = np.ones((2, 3))   # 2x3 ones
print("--- Zeros Array ---")
print(zeros_array, "\n")
print("--- Ones Array ---")
print(ones_array, "\n")

# Step 5: Create a 3x3 identity matrix (Try It Challenge)
identity_matrix = np.eye(3) 
print("--- 3x3 Identity Matrix ---")
print(identity_matrix, "\n")

--- Years of Experience ---
[ 1  3  5  7 10 12 15] 

--- Salary Matrix ---
[[ 50  60  70  75  80]
 [ 80  90 100 110 120]] 

--- Zeros Array ---
[[0. 0.]
 [0. 0.]] 

--- Ones Array ---
[[1. 1. 1.]
 [1. 1. 1.]] 

--- 3x3 Identity Matrix ---
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 



In [2]:
import numpy as np
years_exp = np.array([1, 3, 5, 7, 10])

print("--- Original Array ---")
print("Years of Experience:", years_exp, "\n")

# Step 1: Element-wise addition
exp_plus_5 = years_exp + 5 
print("Years + 5:", exp_plus_5)

# Step 2: Element-wise multiplication
exp_times_2 = years_exp * 2 
print("Years * 2:", exp_times_2)

# Step 3: Dot product
sample1 = np.array([1, 2, 3])
sample2 = np.array([4, 5, 6])
dot_result = np.dot(sample1, sample2)
print("Dot Product:", dot_result, "\n")

# Step 4: Subtraction and Division
exp_minus_1 = years_exp - 1 # Subtract 1 from all values
print("Years - 1 (Subtraction):", exp_minus_1)

exp_div_2 = years_exp / 2 # Divide all values by 2
print("Years / 2 (Division):", exp_div_2, "\n")

# Step 5: Exponential and Logarithm
# np.exp() calculates e^x (Euler's number raised to the power of the array value)
exp_array = np.exp(years_exp) 
print("Exponential (np.exp):", exp_array)

# np.log() calculates the natural logarithm (ln) for each value
log_array = np.log(years_exp) 
print("Logarithm (np.log):", log_array)

--- Original Array ---
Years of Experience: [ 1  3  5  7 10] 

Years + 5: [ 6  8 10 12 15]
Years * 2: [ 2  6 10 14 20]
Dot Product: 32 

Years - 1 (Subtraction): [0 2 4 6 9]
Years / 2 (Division): [0.5 1.5 2.5 3.5 5. ] 

Exponential (np.exp): [2.71828183e+00 2.00855369e+01 1.48413159e+02 1.09663316e+03
 2.20264658e+04]
Logarithm (np.log): [0.         1.09861229 1.60943791 1.94591015 2.30258509]


In [3]:
import numpy as np
years_exp = np.array([1, 3, 5, 7, 10])
salaries = np.array([[50, 60, 70], 
                     [80, 90, 100]])

print("--- Array Indexing & Slicing ---\n")

# Step 1: Access an individual element
print("First year of experience:", years_exp[0])

# Step 2: Slice arrays 
print("First two salaries:", salaries[0, :2]) 

# Step 3: Access all rows for a specific column
print("Second column salaries:", salaries[:, 1])

# Step 4: Negative indexing 
print("Last year of experience:", years_exp[-1], "\n")

# Step 5: Reverse arrays using slicing
reversed_years = years_exp[::-1]
print("Reversed Years of Experience:", reversed_years)

# Step 6: Slice 2D arrays for subgroups of salaries
salary_subgroup = salaries[:, 1:] 
print("\nSalary Subgroup (Last two columns):\n", salary_subgroup)

high_earners = salaries[1, :]
print("\nHigh Earners Subgroup (Second row only):", high_earners)

--- Array Indexing & Slicing ---

First year of experience: 1
First two salaries: [50 60]
Second column salaries: [60 90]
Last year of experience: 10 

Reversed Years of Experience: [10  7  5  3  1]

Salary Subgroup (Last two columns):
 [[ 60  70]
 [ 90 100]]

High Earners Subgroup (Second row only): [ 80  90 100]


In [4]:
import numpy as np

print("--- Array Reshaping & Manipulation ---\n")
base_array = np.arange(1, 7)

# Step 1: Reshape 1D array into 2x3 matrix
reshaped_exp = np.reshape(base_array, (2, 3))
print("Reshaped Experience Array (2x3):\n", reshaped_exp, "\n")

# Step 2: Flatten 2D arrays back into 1D
flattened_exp = reshaped_exp.flatten()
print("Flattened Array:", flattened_exp, "\n")

# Step 3: Transpose example (swaps rows and columns)
print("Transposed Array (3x2):\n", reshaped_exp.T, "\n")

# Step 4: Reshape into different dimensions for modeling
model_data_3x2 = np.reshape(base_array, (3, 2))
print("Reshaped for Modeling (3x2):\n", model_data_3x2, "\n")
model_data_6x1 = np.reshape(base_array, (6, 1))
print("Reshaped as a Column Vector (6x1):\n", model_data_6x1)

--- Array Reshaping & Manipulation ---

Reshaped Experience Array (2x3):
 [[1 2 3]
 [4 5 6]] 

Flattened Array: [1 2 3 4 5 6] 

Transposed Array (3x2):
 [[1 4]
 [2 5]
 [3 6]] 

Reshaped for Modeling (3x2):
 [[1 2]
 [3 4]
 [5 6]] 

Reshaped as a Column Vector (6x1):
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [5]:
import numpy as np

salaries = np.array([[50, 60, 70], 
                     [80, 90, 100]])

print("--- Broadcasting Multiplication ---\n")

print("Original Salaries:\n", salaries, "\n")

# --- Method 1: Scalar Broadcasting ---
scaling_factor = 1.1 
scaled_salaries_scalar = salaries * scaling_factor

print(f"1. Scaled by {scaling_factor} (Scalar Broadcasting):\n", scaled_salaries_scalar, "\n")


# --- Method 2: Array Broadcasting ---
tier_multipliers = np.array([1.0, 1.5, 2.0])
scaled_salaries_array = salaries * tier_multipliers

print("Tier Multipliers Array:", tier_multipliers, "\n")
print("2. Scaled by Array (Column Broadcasting):\n", scaled_salaries_array)

--- Broadcasting Multiplication ---

Original Salaries:
 [[ 50  60  70]
 [ 80  90 100]] 

1. Scaled by 1.1 (Scalar Broadcasting):
 [[ 55.  66.  77.]
 [ 88.  99. 110.]] 

Tier Multipliers Array: [1.  1.5 2. ] 

2. Scaled by Array (Column Broadcasting):
 [[ 50.  90. 140.]
 [ 80. 135. 200.]]


In [6]:
import numpy as np

years_exp = np.array([1, 3, 5, 7, 10])
salaries = np.array([[50, 60, 70], 
                     [80, 90, 100]])

print("--- Advanced Statistical Analysis ---\n")

# Step 1: Compute the median (the middle value when sorted)
print("Median experience:", np.median(years_exp))
print("Median salary:", np.median(salaries), "\n")

# Step 2: Compute percentiles
print("50th Percentile of experience:", np.percentile(years_exp, 50))
print("75th Percentile of salaries:", np.percentile(salaries, 75), "\n")
print("25th Percentile of salaries (per column):")
print(np.percentile(salaries, 25, axis=0))

--- Advanced Statistical Analysis ---

Median experience: 5.0
Median salary: 75.0 

50th Percentile of experience: 5.0
75th Percentile of salaries: 87.5 

25th Percentile of salaries (per column):
[57.5 67.5 77.5]


In [7]:
import numpy as np
years_exp = np.array([1, 3, 5, 7, 10])
salaries = np.array([[50, 60, 70], 
                     [80, 90, 100]])

print("--- Array Transformations ---\n")

# Step 1: Use np.sqrt() and np.log()
sqrt_exp = np.sqrt(years_exp)
print("Square Root of Experience:\n", sqrt_exp, "\n")
log_salaries = np.log(salaries)
print("Natural Log of Salaries:\n", log_salaries, "\n")


print("--- Custom Functions with apply_along_axis ---\n")
def calculate_range(data_array):
    """Calculates the difference between the highest and lowest values in an array."""
    return np.max(data_array) - np.min(data_array)

# Step 3: Apply the custom function
salary_ranges_per_row = np.apply_along_axis(calculate_range, 1, salaries)
salary_ranges_per_col = np.apply_along_axis(calculate_range, 0, salaries)

print("Original Salaries Matrix:\n", salaries, "\n")
print("Salary Spread per Row (axis=1):", salary_ranges_per_row)
print("Salary Spread per Column (axis=0):", salary_ranges_per_col)

--- Array Transformations ---

Square Root of Experience:
 [1.         1.73205081 2.23606798 2.64575131 3.16227766] 

Natural Log of Salaries:
 [[3.91202301 4.09434456 4.24849524]
 [4.38202663 4.49980967 4.60517019]] 

--- Custom Functions with apply_along_axis ---

Original Salaries Matrix:
 [[ 50  60  70]
 [ 80  90 100]] 

Salary Spread per Row (axis=1): [20 20]
Salary Spread per Column (axis=0): [30 30 30]


In [8]:
import numpy as np
years_exp = np.array([1, 3, 5, 7, 10])
salaries = np.array([[50, 60, 70], 
                     [80, 90, 100]])

print("--- Column Statistics ---\n")

print("Original Salaries Matrix:\n", salaries, "\n")

# Step 1: Compute overall column statistics (axis=0 means "down the columns")
col_mean = np.mean(salaries, axis=0)
col_median = np.median(salaries, axis=0)

print("Mean per column:  ", col_mean)
print("Median per column:", col_median, "\n")

# Step 2: Apply np.square() and np.exp()
squared_exp = np.square(years_exp)
print("Original Experience:", years_exp)
print("Squared Experience: ", squared_exp, "\n")
exp_years = np.exp(years_exp) 
print("Exponential of Experience (e^x):\n", exp_years)

--- Column Statistics ---

Original Salaries Matrix:
 [[ 50  60  70]
 [ 80  90 100]] 

Mean per column:   [65. 75. 85.]
Median per column: [65. 75. 85.] 

Original Experience: [ 1  3  5  7 10]
Squared Experience:  [  1   9  25  49 100] 

Exponential of Experience (e^x):
 [2.71828183e+00 2.00855369e+01 1.48413159e+02 1.09663316e+03
 2.20264658e+04]


In [9]:
import numpy as np
import pandas as pd

# Re-creating the imported DataFrame from previous steps so the code runs
np.random.seed(42) # Using a seed so the random numbers stay the same for review
data = np.random.randint(1, 50, size=(5, 3))
df_imported = pd.DataFrame(data, columns=['X', 'Y', 'Z'])

print("--- Modifying and Saving DataFrames ---\n")
print("Original Imported DataFrame:\n", df_imported, "\n")

# Step 1: Add a new calculated column (Sum of X and Y)
df_imported['Sum_XY'] = df_imported['X'] + df_imported['Y']
print("DataFrame with New 'Sum_XY' Column:\n", df_imported, "\n")

# Step 2: Save the modified DataFrame to a NEW CSV file
df_imported.to_csv('modified_data.csv', index=False)
print("Success! Modified data saved to 'modified_data.csv'.")

--- Modifying and Saving DataFrames ---

Original Imported DataFrame:
     X   Y   Z
0  39  29  15
1  43   8  21
2  39  19  23
3  11  11  24
4  36  40  24 

DataFrame with New 'Sum_XY' Column:
     X   Y   Z  Sum_XY
0  39  29  15      68
1  43   8  21      51
2  39  19  23      58
3  11  11  24      22
4  36  40  24      76 

Success! Modified data saved to 'modified_data.csv'.


In [10]:
import pandas as pd
import numpy as np

print("--- Testing Groupby Logic on Dummy Data ---\n")

# Step 1: Load the dummy data you already have
df_data = pd.read_csv('modified_data.csv')
print("Loaded Dataset:\n", df_data.head(), "\n")

# Step 2: Select relevant columns (the ones that actually exist!)
df_subset = df_data[['X', 'Y', 'Sum_XY']]
print("Subset of Data:\n", df_subset.head(), "\n")

# Step 3: Clean the data
df_clean = df_subset.dropna().copy()

# Step 4: Categorize X into groups 
# (Assigns 'High' if X is 30 or greater, otherwise 'Low')
df_clean['X_Category'] = np.where(df_clean['X'] >= 30, 'High', 'Low')

# Step 5: Group data by the new category, compute average of Y
grouped_data = df_clean.groupby(['X_Category'])['Y'].mean()
print("Grouped Average of Y:\n", grouped_data.head(), "\n")

# Step 6: Reset index for readability
grouped_data = grouped_data.reset_index()
print("Formatted Grouped Data:\n", grouped_data.head())

--- Testing Groupby Logic on Dummy Data ---

Loaded Dataset:
     X   Y   Z  Sum_XY
0  39  29  15      68
1  43   8  21      51
2  39  19  23      58
3  11  11  24      22
4  36  40  24      76 

Subset of Data:
     X   Y  Sum_XY
0  39  29      68
1  43   8      51
2  39  19      58
3  11  11      22
4  36  40      76 

Grouped Average of Y:
 X_Category
High    24.0
Low     11.0
Name: Y, dtype: float64 

Formatted Grouped Data:
   X_Category     Y
0       High  24.0
1        Low  11.0


In [11]:
import pandas as pd
import numpy as np

print("--- Try It Challenges (Dummy Data Version) ---\n")

# Load and prep the data (same as before)
df_data = pd.read_csv('modified_data.csv')
df_data['X_Category'] = np.where(df_data['X'] >= 30, 'High', 'Low')

# Challenge 1 & 2: Change grouping and compute standard deviation
# We group by X_Category and find the standard deviation (spread) of Y
grouped_std = df_data.groupby(['X_Category'])['Y'].std().reset_index()
print("1 & 2. Standard Deviation of Y per Category:\n", grouped_std, "\n")

# Challenge 3: Top values
# Since we don't have 10 countries, we will find the top 3 rows with the highest Sum_XY
top_3_sums = df_data.sort_values(by='Sum_XY', ascending=False).head(3)
print("3. Top 3 Highest Sum_XY Records:\n", top_3_sums[['X', 'Y', 'Sum_XY']])

--- Try It Challenges (Dummy Data Version) ---

1 & 2. Standard Deviation of Y per Category:
   X_Category          Y
0       High  13.686977
1        Low        NaN 

3. Top 3 Highest Sum_XY Records:
     X   Y  Sum_XY
4  36  40      76
0  39  29      68
2  39  19      58
